### ISSUE TITLE
TAS build

### ISSUE THREAD

**Issue by iMonZ** [triforce-percent/triforce-percent#2]
Thank you so much for this mod!
I just love it. Looked through the code and it must be so much work.

But is it possible to patch this rom over an official game with TAS? If yes how? Thanks!

**Comment by sauraen** [comment]
The primary purpose of this project / repo was to produce the files needed for TASBot to take control of the game and patch it live. The build tools here also output a romhack version of the project for testing (given that you supply an original 1.0 ROM), but that's secondary.

The TAStm32 custom firmware and host code are here: https://github.com/sauraen/tastm32/tree/OoTHyperspeed
The Twitch frontend is here: https://github.com/TheMas3212/udp-twitch-chat-proxy

We were planning to eventually write a guide for how to do this, but there hasn't been very much interest so that hasn't happened yet. Rough list of what you will need:
- TAStm32 V2 or V3 board
- Four N64 controller cables, at least two with the +3.3V line not connected, and one ideally with a switch to manual control
- Either the speedrunning skill to do the ACE setup yourself (it's hard), or the shortcut ROM and a flashcart (you can build the shortcut ROM from this repo given that you supply an original 1.0 ROM)

**Comment by sauraen** [comment]
If you have these things and you would like a more detailed guide, feel free to reopen. Also feel free to ask more in the TASBot discord http://discord.tas.bot/

**Comment by iMonZ** [comment]
> The primary purpose of this project / repo was to produce the files needed for TASBot to take control of the game and patch it live. The build tools here also output a romhack version of the project for testing (given that you supply an original 1.0 ROM), but that's secondary.
> 
> The TAStm32 custom firmware and host code are here: https://github.com/sauraen/tastm32/tree/OoTHyperspeed The Twitch frontend is here: https://github.com/TheMas3212/udp-twitch-chat-proxy
> 
> We were planning to eventually write a guide for how to do this, but there hasn't been very much interest so that hasn't happened yet. Rough list of what you will need:
> 
> * TAStm32 V2 or V3 board
> * Four N64 controller cables, at least two with the +3.3V line not connected, and one ideally with a switch to manual control
> * Either the speedrunning skill to do the ACE setup yourself (it's hard), or the shortcut ROM and a flashcart (you can build the shortcut ROM from this repo given that you supply an original 1.0 ROM)

Thank you so much! I will definitely try this :)

**Comment by iMonZ** [comment]
My goal is to get this rom running on an unmodfied OG N64
