### ISSUE TITLE
Modded rom download

### ISSUE THREAD

**Issue by xDAVIDx93** [triforce-percent/triforce-percent#3]
Hey just wondering if you could release this as a modded rom so we the players can download and play it? 😀

**Comment by sauraen** [comment]
ROMs cannot be legally distributed, so no we cannot. We have released all the code and assets our team created, not including anything copyrighted by Nintendo, so you can build those things into a ROM if you provide an original US 1.0 ROM as input.

**Comment by avengah** [comment]
How about a delta patch? Because that linux method looks very complicated, and deltapatcher should be much more accessible for people. Thanks!

**Comment by sauraen** [comment]
There's a few reasons we didn't release a patch file of the same contents that we've released here on GitHub.

1. People would still have to dump their own 1.0 ROM and then run it through a decompressor, and make sure that gave exactly the same output as the input to the patch process. This would still require the user to dig into some tools. Patching relative to the compressed ROM would mean the patch file would encode the whole uncompressed ROM, which would not be legal to distribute.
2. This project was developed on console only, and has some issues with popular emulators, especially if they're in recompiler mode. Also, as explained on the website and readme, this repo does not include any content copyrighted by Nintendo (e.g. textures ripped from OoT, the BotW models) because we can't legally distribute that content, so there will be missing content in the "romhack" build. The easier we make it for non-technical people to play it, the more complaints we will receive about these things. Since we can't distribute Nintendo content and we don't have the resources to implement workarounds for emulator inaccuracies, these complaints won't be constructive.
3. The GitHub release was primarily made for developers--either folks wanting to use our code or assets in their romhack, or folks wanting to use our tools to make a TAS-injectible "RAMhack" like we did. If people want to just play it, we don't have a problem with that of course, but the project was created to make the GDQ performance happen, not to make a playable game for the community. With a couple very minor exceptions, there really isn't anything in Triforce% which wasn't shown at GDQ.

**Comment by avengah** [comment]
I see. Thanks for explaining. In my experience, deltapatcher doesn't require the rom to be decompressed and it doesn't require any copyrighted content, because all a patch file is, is a list of changes. So I've seen patches listed with a simple notice like "Only works with ROM version x [U] [!}" etc. Now there's still the issue of potentially breaking copyright if the patched output ROM contains copyrighted content, even though the patch itself may not; if that is a concern, then in the past people have worked around this by swapping characters out. I realise it's not the same (and if the player is going for the authentic experience as seen on AGDQ they might be unhappy), but it is quite possibly the safest option: no copyrighted content in the patch file and no copyrighted content in the output file that wasn't already in the ROM (which you don't supply).

But I appreciate that it's been a lot of work for your team, and the end product was presented in the absolute best way possible in my opinion - the money raised was incredible! Well done to each and every one of you for your outstanding achievements! I wouldn't expect you to drop everything and give yourself extra work to create a patch that works on emulators without it including copyrighted content.

And given that this is the Internet, no doubt someone else will sooner or later create a patch or even a prepatched ROM. (If they don't care about copyright laws and are prepared to risk incurring the wrath of Nintendo!)

**Comment by sauraen** [comment]
Right, so since the output ROM is an uncompressed ROM, if the input ROM was a compressed ROM then the patch file would have to encode all the uncompressed data in it, including all the original copyrighted data. The only way to ensure that the patch file only contained our changes would be to have the input ROM also be uncompressed.

Compressing the output ROM and doing the patch between the original compressed ROM and that version might or might not work, but it's riskier. Suppose we changed one byte in a file which is normally compressed, that might lead to most of the compressed file being different and then the patch file basically just containing the copyrighted data.
